### ISSUE TITLE
[SUGGESTION] Pufferpups should eat carrots and moan when doing so

### ISSUE THREAD

**Issue by Sunconure11** [MsRandom/BeastsMod#16]
https://www.youtube.com/watch?v=qKxfWd79HFI

**Comment by IdrisQe** [comment]
Please do not add this.
The pufferfish in that video is actually making _choking_ sounds because it's both suffocating and unable to swallow the carrot. The only reason it's biting is out of defensive self-preservation reflexes. They're basically torturing the fish before they kill it.

**Comment by Coda1552** [comment]
Hello. as IdrisQe said, the pufferfish is dying in the video. We will probably not implement this because the pufferfish is dying and being prepared for fugu.
