### ISSUE TITLE
Issues with Jellywood Double Slabs (possibly more?

### ISSUE THREAD

**Issue by katubug** [MsRandom/BeastsMod#18]
Hi! I was looking through my startup logs for something else and happened upon a handful of errors for version 1.1.2. My forge version is 2847.

Here's my log file: https://pastebin.com/H2TRfDdW

And since one of the items mentioned was a Jellywood Double Slab, I went ahead and put two of the slabs together, and got this:
![2019-12-17_21 37 36](https://user-images.githubusercontent.com/20935286/71053944-cc124280-2115-11ea-857b-6fc517193d71.png)

I don't think any of my other mods could be causing conflicts like that, but please let me know if you'd like a modlist. :)

**Comment by MsRandom** [comment]
The startup errors is a known issue, but I didn't know about the double slab problem, I'll look into it as soon as I can.

**Comment by katubug** [comment]
Thanks a bunch!

**Comment by Coda1552** [comment]
This has been fixed (it was actually fixed a while ago, oops). Closing the issue.
