### ISSUE TITLE
Biome features not generating with RTG

### ISSUE THREAD

**Issue by Excederus** [MsRandom/BeastsMod#20]
The Biome itself is "there" (I can find it with the Nature's Compass Mod) but there are no features of the Dried Reef Biome generating and none of the entities spawn.
It basically is a plains biome (oddly it also shows as plains in F3) but detected as Dried Reef from the Nature's Compass.

UPDATE: The biome generates fine if using default world gen with still all other mods present

![Screenshot](https://user-images.githubusercontent.com/29584262/71526645-2199dc80-28d8-11ea-857c-995ca24b699b.png)

![Screenshot2](https://user-images.githubusercontent.com/29584262/71526703-5d34a680-28d8-11ea-872c-8b8300fdcdc7.png)

**Comment by Excederus** [comment]
Modlist: https://pastebin.com/UaVQa0ba

**Comment by JoelZBub** [comment]
This is the same experience I had using RTG and Beasts.
