### ISSUE TITLE
Crash on world launch

### ISSUE THREAD

**Issue by skyeblueocean** [MsRandom/BeastsMod#21]
Crash - com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException

Full report - https://pastebin.com/mZz2N063
My mod list - https://pastebin.com/82VY2vp5
I've tried disabling a couple of my more recently added mods but still get a crash report when I try to load a world. Any other mods listed in the report are disabled when trying to run Beasts.

**Comment by MsRandom** [comment]
It's a known issue, it seems to only happen with a few configurations, it should be fixed in the next update.
