### ISSUE TITLE
Extreme tps spike while generating the biome

### ISSUE THREAD

**Issue by Zack7292** [MsRandom/BeastsMod#25]
when generating your mod's biome, the tps (that you can verify by doing /forge tps) is passing (for me ) from 20/20 to 3/20 tps, which make it totally unplayable for a good minute, i think fixing this should be pretty important to make you pack playable in actual packs

**Comment by Coda1552** [comment]
Thank you for reporting this, we'll look into it

**Comment by MsRandom** [comment]
That should already be fixed, there just isn't any builds yet that have the fix applied.

**Comment by Zack7292** [comment]
ok thx :)
